//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 11:25:40 PM EET 
//


package soapservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="medications" type="{http://springsoap}ArrayOfMeds"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medications"
})
@XmlRootElement(name = "medResponse")
public class MedResponse {

    @XmlElement(required = true)
    protected ArrayOfMeds medications;

    /**
     * Gets the value of the medications property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMeds }
     *     
     */
    public ArrayOfMeds getMedications() {
        return medications;
    }

    /**
     * Sets the value of the medications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMeds }
     *     
     */
    public void setMedications(ArrayOfMeds value) {
        this.medications = value;
    }

}
