//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 11:25:40 PM EET 
//


package soapservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soapservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soapservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PatientHistoryRequest }
     * 
     */
    public PatientHistoryRequest createPatientHistoryRequest() {
        return new PatientHistoryRequest();
    }

    /**
     * Create an instance of {@link PatientHistoryResponse }
     * 
     */
    public PatientHistoryResponse createPatientHistoryResponse() {
        return new PatientHistoryResponse();
    }

    /**
     * Create an instance of {@link ArrayOfActivities }
     * 
     */
    public ArrayOfActivities createArrayOfActivities() {
        return new ArrayOfActivities();
    }

    /**
     * Create an instance of {@link MedRequest }
     * 
     */
    public MedRequest createMedRequest() {
        return new MedRequest();
    }

    /**
     * Create an instance of {@link MedResponse }
     * 
     */
    public MedResponse createMedResponse() {
        return new MedResponse();
    }

    /**
     * Create an instance of {@link ArrayOfMeds }
     * 
     */
    public ArrayOfMeds createArrayOfMeds() {
        return new ArrayOfMeds();
    }

    /**
     * Create an instance of {@link RecommendRequest }
     * 
     */
    public RecommendRequest createRecommendRequest() {
        return new RecommendRequest();
    }

    /**
     * Create an instance of {@link RecommendResponse }
     * 
     */
    public RecommendResponse createRecommendResponse() {
        return new RecommendResponse();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link Med }
     * 
     */
    public Med createMed() {
        return new Med();
    }

}
